apiVersion: v1
kind: Service
metadata:
  labels:
    app: exampleapp
  name: exampleapp
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: exampleapp
  sessionAffinity: None
  type: ClusterIP
